### PR TITLE
Drop Python 2.6 on appveyor, install 'grpcio' unconditionally.

### PR DESCRIPTION
**Pull request by tseaver**
`grpcio` 0.14.0 installs without errors on Python 3.4+.

See #1863, failures after merging #1877.

### CODE REVIEW

**Comment by daspecster** [comment]
@tseaver, do you have appveyor hooked up to your username or if you want I can copy this branch to my repo and run it.

**Comment by tseaver** [comment]
Oops, I was out-of-sync and merged ahead of seeing your build finish.

**Comment by daspecster** [comment]
Np, I have it building master now https://ci.appveyor.com/project/daspecster/gcloud-python-pjqjn

**Comment by daspecster** [comment]
@tseaver lots of
`ImportError: cannot import name timestamp_pb2`
https://ci.appveyor.com/project/daspecster/gcloud-python-pjqjn/build/1.0.5.master/job/9yeww3g7vk6wvdcr#L543

**Comment by tseaver** [comment]
Crap.

**Comment by daspecster** [comment]
A little different for py3,
https://ci.appveyor.com/project/daspecster/gcloud-python-pjqjn/build/1.0.5.master/job/0dn0nee07e773mc4#L194

**Comment by tseaver** [comment]
Ugh.  I'm not sure what to say:  somebody has hosed the `google` namespace package.

**Comment by daspecster** [comment]
For windows specifically?

**Comment by daspecster** [comment]
It's still that unbuilt egg error for py3 https://ci.appveyor.com/project/daspecster/gcloud-python-pjqjn/build/1.0.5.master/job/0dn0nee07e773mc4#L149

And yeah for py2 it can't import timestamp_pb2 from google.protobuf.
https://ci.appveyor.com/project/daspecster/gcloud-python-pjqjn/build/1.0.5.master/job/f8l9c4aixytmd4m0#L551

**Comment by daspecster** [comment]
Could try and switching `protobuf == 3.0.0b2` from `3.0.0b3`?

**Comment by tseaver** [comment]
Maybe we should revert this PR (or at least the bit which globally installs `grpcio`) and just leave Appveyor borken until a fix is released for https://github.com/grpc/grpc/issues/6939.

**Comment by daspecster** [comment]
Wouldn't we want it this way once https://github.com/grpc/grpc/issues/6939 is resolved?
